### ISSUE TITLE
[FEATURE] Make REDIRECT_URI actually redirect to the proper page

### ISSUE THREAD

**Issue by cire3wastaken** [darverdevs/ESL-Suggestions#2]
When I attempt to login to my account to delete/warn a user, it brings me to login. However, since REDIRECT_URI isn't fully implemented, it instead redirects me to the homepage instead of that user's profile, which makes moderating very difficult.

Make REDIRECT_URI work.

wo shi yi ge hao ren

**Comment by ColdDev** [comment]
This is a V2 fix
