### ISSUE TITLE
[BUG] MARK AS READ button for warns does not work

### ISSUE THREAD

**Issue by cire3wastaken** [darverdevs/ESL-Suggestions#3]
If you are warned, MARK AS READ button doesn't work.

**To Reproduce**
1) vote bomb
2) get warned
3) click the MARK AS READ button

**Expected behavior**
Closes the warn screen

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Brave
 - Version idfk

**Comment by ColdDev** [comment]
@cire3wastaken Additional information is required: does an error notification pop up when you click the button? What happens when you click it?

**Comment by cire3wastaken** [comment]
Closing because fixed
